version: '3'
services:
  salsamish-db:
    container_name: salsamish-db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: salsamish
      MONGO_NON_ROOT_USERNAME: salsa
      MONGO_NON_ROOT_PASSWORD: example
    volumes:
      - ./mongodb/setup/:/docker-entrypoint-initdb.d/
      - ./mongodb/data:/data/db
    ports:
      - 27017-27019:27017-27019
    networks:
       - frontend
       - backend
  salsamish-admin:
    container_name: salsamish-admin
    depends_on:
      - salsamish-db
    image: salsamish-admin:latest
    environment:
      DB_HOSTNAME: salsamish-db
      DB_USERNAME: salsa
      DB_PASSWORD: example
      AUTH_SECRET: development
    volumes:
      - ./images/employees:/app/build/images/employees
    ports:
      - 5000:3001
    networks:
       - backend
  salsamish-website:
    container_name: salsamish-website
    depends_on:
      - salsamish-db
    image: salsamish-website:latest
    environment:
      DB_HOSTNAME: salsamish-db
      DB_USERNAME: salsa
      DB_PASSWORD: example
    volumes:
      - ./images/employees:/app/public/images/employees
    ports:
      - 4000:4000
    networks:
       - frontend
networks:
  frontend:
  backend: